timeframes: ["1m", "5m"]
dte_buckets: [[7,10],[20,30],[35,45]]
strike_rules:
  - {type: "delta", value: 0.30}
  - {type: "delta", value: 0.15}
  - {type: "pct_otm", value: 4}
spread_widths: [1, 2, 3]
profit_target_pct: [0.5, 1.0, 1.5]
max_loss_mult_credit: [1.0, 1.5, 2.0]
time_stop_days_before_expiry: [1, 3]
liquidity:
  max_spread_pct: 0.05
  min_oi: 100
  min_volume: 20
thresholds:
  min_win_pct: 0.60
  min_sharpe: 0.8
  min_samples: 50
